### PR TITLE
Graphql api impl

### PR DESCRIPTION
**Pull request by laura-wenning**
Changes
- Adds graphql and apollo client stuff
- Adds resolvers and typedefs for the bulk of our alpha usecase

### CODE REVIEW

**Review by lucyawrey — CHANGES_REQUESTED** [review]
This is very large and I tried my best to look over it all. I gave a bit of feedback here, but we should go over the whole thing in more depth tomorrow.

**Comment by lucyawrey** [comment]
@laura-wenning I know I asked you to remove the npm package "micro" as I thought it was not necessary. Lacking it is causing the production build to fail, but not the dev build. Something for us to look into

**Comment by laura-wenning** [comment]
> @laura-wenning I know I asked you to remove the npm package "micro" as I thought it was not necessary. Lacking it is causing the production build to fail, but not the dev build. Something for us to look into

It doesn't cause the dev build to fail, but it is required for the endpoint to actually work, which is strange. I've added it back in.

**Review by lucyawrey — APPROVED** [review]
Good to go

**Pull request merged**
